# MUSUBI Project Configuration
name: YAGOKORO
description: AGI実現に向けたLLM・GraphRAG・オントロジー統合システム
locale: ja
version: "4.0.0"
created: 2025-12-28
updated: 2025-12-31

# Technology Stack
tech_stack:
  approach: monorepo-library-first
  languages:
    - typescript
  runtime: node-20-lts
  package_manager: pnpm

# Architecture
architecture:
  pattern: hexagonal-ddd
  layers:
    - domain
    - application
    - infrastructure
    - interface

# Libraries
libraries:
  core:
    - name: "@yagokoro/domain"
      path: "libs/domain"
      purpose: "ドメインモデル・エンティティ・値オブジェクト"
    - name: "@yagokoro/graphrag"
      path: "libs/graphrag"
      purpose: "GraphRAGコアエンジン（抽出・推論・クエリ）"
    - name: "@yagokoro/nlq"
      path: "libs/nlq"
      purpose: "自然言語クエリ処理（NL→Cypher変換）"
    - name: "@yagokoro/hallucination"
      path: "libs/hallucination"
      purpose: "ハルシネーション検出・整合性チェック"
    - name: "@yagokoro/temporal"
      path: "libs/temporal"
      purpose: "時系列分析・トレンド検出（v4.0.0新規）"
    - name: "@yagokoro/researcher"
      path: "libs/researcher"
      purpose: "研究者ネットワーク分析（v4.0.0新規）"
  infrastructure:
    - name: "@yagokoro/neo4j"
      path: "libs/neo4j"
      purpose: "Neo4jグラフデータベース接続・リポジトリ"
    - name: "@yagokoro/vector"
      path: "libs/vector"
      purpose: "Qdrantベクトルストア接続・埋め込み"
  interface:
    - name: "@yagokoro/mcp"
      path: "libs/mcp"
      purpose: "MCPサーバー・ツール・リソース"
    - name: "@yagokoro/cli"
      path: "libs/cli"
      purpose: "CLIコマンド実装"

# Applications
applications:
  - name: "yagokoro"
    path: "apps/yagokoro"
    purpose: "メインアプリケーション・MCPサーバー"

# Domain Entities
domain_entities:
  - AIModel
  - Benchmark
  - Community
  - Concept
  - Organization
  - Person
  - Publication
  - Technique

# Phase
current_phase: "Phase 4 - v5.0.0 Planned"
phases:
  - id: 1
    name: "Generative AI系譜GraphRAGシステム (v1.0-v2.0)"
    status: "complete"
  - id: 2
    name: "自動関係抽出・論文取り込み (v3.0.0)"
    status: "complete"
  - id: 3
    name: "時系列分析・研究者ネットワーク (v4.0.0)"
    status: "complete"
  - id: 4
    name: "多言語論文対応 (v5.0.0)"
    status: "planned"
  - id: 5
    name: "AGIコア機能"
    status: "planned"

# v4.0.0 Features
v4_features:
  - id: "F-004"
    name: "時系列分析"
    package: "@yagokoro/temporal"
    priority: P0
    status: "complete"
    tests: 113
  - id: "F-005"
    name: "研究者ネットワーク"
    package: "@yagokoro/researcher"
    priority: P0
    status: "complete"
    tests: 94
  - id: "F-006"
    name: "CLI統合"
    package: "@yagokoro/cli"
    priority: P0
    status: "complete"
    tests: 47
  - id: "F-007"
    name: "MCP統合"
    package: "@yagokoro/mcp"
    priority: P0
    status: "complete"
    tests: 51
